using System;
using System.IO;
using System.Text;
using RimWorld;
using UnityEngine;
using Verse;

namespace D4egon.RimRimModelEditor.Logic
{
    /// <summary>
    /// Saves studio snapshots as portrait paintings into a single shared mod folder.
    /// Each portrait adds:
    ///   Textures/Things/Building/Art/{defName}.png
    ///   Defs/Things/{defName}.xml
    ///
    /// About.xml is written once on first use and never overwritten, so you can
    /// customise the mod name/description without it being reset.
    ///
    /// If a portrait with the same defName already exists inside the mod, the new
    /// one is automatically suffixed: Portrait_Bob → Portrait_Bob_2 → Portrait_Bob_3 …
    /// </summary>
    public static class PortraitExporter
    {
        public static void Export(Texture2D portrait, string defName, string outputModFolder)
        {
            if (portrait == null) throw new ArgumentNullException("portrait");
            if (string.IsNullOrWhiteSpace(defName)) throw new ArgumentException("defName required");

            // ── 0. Resolve a unique defName within the shared mod folder ───────
            // Uniqueness is determined by whether the PNG already exists — the mod
            // folder itself is shared, so we never check the folder for uniqueness.
            string resolvedDefName = ResolveUniqueDefName(defName, outputModFolder);
            bool wasRenamed = resolvedDefName != defName;

            // ── 1. Save PNG ────────────────────────────────────────────────────
            string texDir  = Path.Combine(outputModFolder, "Textures", "Things", "Building", "Art");
            Directory.CreateDirectory(texDir);
            string texFile = Path.Combine(texDir, resolvedDefName + ".png");

            byte[] png = ScreenshotCapture.EncodePNG(portrait);
            if (png == null) throw new InvalidOperationException("EncodeToPNG unavailable.");
            File.WriteAllBytes(texFile, png);

            // ── 2. Write ThingDef XML ──────────────────────────────────────────
            string defDir  = Path.Combine(outputModFolder, "Defs", "Things");
            Directory.CreateDirectory(defDir);
            string defFile = Path.Combine(defDir, resolvedDefName + ".xml");
            File.WriteAllText(defFile, BuildThingDefXml(resolvedDefName), Encoding.UTF8);

            // ── 3. Write About.xml once — never overwrite so user edits persist ─
            string aboutDir  = Path.Combine(outputModFolder, "About");
            string aboutFile = Path.Combine(aboutDir, "About.xml");
            if (!File.Exists(aboutFile))
            {
                Directory.CreateDirectory(aboutDir);
                File.WriteAllText(aboutFile, BuildAboutXml(), Encoding.UTF8);
            }

            string msg = wasRenamed
                ? $"'{defName}' already existed — added as '{resolvedDefName}' to {outputModFolder}"
                : $"Portrait '{resolvedDefName}' added to {outputModFolder}";

            Messages.Message(msg, MessageTypeDefOf.TaskCompletion, false);
        }

        /// <summary>
        /// Returns a defName that has no matching PNG inside the mod's texture folder.
        /// Appends _2, _3, … until a free name is found.
        /// </summary>
        private static string ResolveUniqueDefName(string baseName, string modFolder)
        {
            string texDir = Path.Combine(modFolder, "Textures", "Things", "Building", "Art");

            // Base name is free — use it as-is.
            if (!File.Exists(Path.Combine(texDir, baseName + ".png")))
                return baseName;

            int n = 2;
            while (true)
            {
                string candidate = $"{baseName}_{n}";
                if (!File.Exists(Path.Combine(texDir, candidate + ".png")))
                    return candidate;
                n++;
            }
        }

        private static string BuildThingDefXml(string defName)
        {
            string label = defName.Replace("_", " ").ToLower();
            return
$@"<?xml version=""1.0"" encoding=""UTF-8""?>
<!-- Generated by RimRimModelEditor — place this mod folder in your Mods directory -->
<!-- Requires Vanilla Expanded Framework (VEF) for PlaceWorker_OnWall placement logic. -->
<Defs>

  <ThingDef ParentName=""BuildingBase"">
    <defName>{defName}</defName>
    <label>{label}</label>
    <description>A portrait painted by hand.  Somehow it looks exactly like a colonist.</description>
    <thingClass>Building</thingClass>
    <category>Building</category>
    <altitudeLayer>BuildingOnTop</altitudeLayer>
    <passability>PassThroughOnly</passability>
    <constructEffect>Clean</constructEffect>
    <fillPercent>0</fillPercent>
    <size>(1,1)</size>
    <graphicData>
      <texPath>Things/Building/Art/{defName}</texPath>
      <graphicClass>Verse.Graphic_Single</graphicClass>
      <shaderType>Cutout</shaderType>
      <drawSize>(1,1)</drawSize>
    </graphicData>
    <rotatable>false</rotatable>
    <placeWorkers>
      <li>VEF.Buildings.PlaceWorker_OnWall</li>
    </placeWorkers>
    <building>
      <isEdifice>false</isEdifice>
      <canPlaceOverWall>true</canPlaceOverWall>
    </building>
    <statBases>
      <MaxHitPoints>50</MaxHitPoints>
      <Beauty>15</Beauty>
      <WorkToBuild>5000</WorkToBuild>
      <Mass>2</Mass>
      <Flammability>4.0</Flammability>
    </statBases>
    <costList>
      <Cloth>5</Cloth>
    </costList>
    <designationCategory>Furniture</designationCategory>
    <uiOrder>2450</uiOrder>
    <constructEffect>ConstructMetal</constructEffect>
    <repairEffect>Repair</repairEffect>
    <leaveResourcesWhenKilled>false</leaveResourcesWhenKilled>
  </ThingDef>

</Defs>
";
        }

        private static string BuildAboutXml()
        {
            return
@"<?xml version=""1.0"" encoding=""UTF-8""?>
<ModMetaData>
  <name>My Portraits</name>
  <author>RimRimModelEditor</author>
  <description>Portrait paintings generated by RimRimModelEditor.
Each painting can be placed on a wall in-game via the Furniture architect tab.</description>
  <supportedVersions>
    <li>1.5</li>
    <li>1.6</li>
  </supportedVersions>
</ModMetaData>
";
        }
    }
}
