#pragma warning disable CS8600, CS8604
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using D4egon.RimRimModelEditor.Model;
using UnityEngine;
using Verse;
using RimWorld;

namespace D4egon.RimRimModelEditor.Logic
{
    /// <summary>
    /// Generates RimWorld-compatible Def XML from the current studio state.
    /// Output can be dropped directly into a mod's Defs/ folder and loaded by the game.
    /// </summary>
    public static class XmlExporter
    {
        // ── 1. LIVE PREVIEW STRING ────────────────────────────────────────────

        public static string GeneratePreviewString(EditorState state)
        {
            if (state.SelectedObject == null) return "<!-- No object selected -->";
            return GenerateDefXmlString(state.SelectedObject);
        }

        // ── 2. MULTI-FILE EXPORT ──────────────────────────────────────────────

        public static List<string> Export(
            EditorState state, string outputDir, bool includeTextures, bool overwrite)
        {
            var errors = new List<string>();
            if (state.ActiveScene.Count == 0)
            {
                errors.Add("Scene is empty — nothing to export.");
                return errors;
            }

            try
            {
                Directory.CreateDirectory(outputDir);

                foreach (var obj in state.ActiveScene)
                {
                    string filePath = Path.Combine(outputDir, $"{obj.DefName}.xml");
                    File.WriteAllText(filePath, WrapInDefsDocument(GenerateDefXmlString(obj)),
                        Encoding.UTF8);
                }

                if (includeTextures)
                    CopySceneTextures(state, outputDir, overwrite, errors);

                Messages.Message("Export successful.", MessageTypeDefOf.PositiveEvent, false);
            }
            catch (Exception ex) { errors.Add($"Export failed: {ex.Message}"); }

            return errors;
        }

        // ── 3. ALL-LAYERS EXPORT ──────────────────────────────────────────────

        /// <summary>
        /// Serialises every layer of every scene object into its own ThingDef block with
        /// all studio properties (texPath, graphicClass, drawSize, drawOffset, color tint,
        /// opacity, rotation, body-type variant).  Output is a valid Defs XML document that
        /// can be dropped into a mod's Defs/ folder. Layers that lack a texture path are
        /// included as comments so the user still sees the full picture.
        /// </summary>
        public static string GenerateAllLayersXml(EditorState state)
        {
            if (state == null || state.ActiveScene.Count == 0)
                return WrapInDefsDocument("<!-- Scene is empty -->");

            var sb = new StringBuilder();
            sb.AppendLine("<!-- Generated by RimRimModelEditor — All-Layers Export -->");
            sb.AppendLine("<!-- Each layer is exported as an independent ThingDef.   -->");
            sb.AppendLine("<!-- Adjust ParentName / defName before use in a real mod.-->");
            sb.AppendLine();

            foreach (var obj in state.ActiveScene)
            {
                sb.AppendLine($"  <!-- ═══════════ Scene Object: {obj.DefName} ═══════════ -->");
                sb.AppendLine($"  <!-- RootScale=({obj.RootScale.x:F2},{obj.RootScale.y:F2})"
                            + $"  RootPos=({obj.RootPosition.x:F3},{obj.RootPosition.y:F3})"
                            + $"  RootRot={obj.RootRotation:F1}° -->");
                sb.AppendLine();

                // Sort by priority so the XML read order mirrors draw order.
                var sorted = new List<LayerData>(obj.Layers);
                sorted.Sort((a, b) => a.Priority.CompareTo(b.Priority));

                foreach (var layer in sorted)
                {
                    bool hasPath = !string.IsNullOrEmpty(layer.TexturePath);

                    // Layers without a texture path become comments.
                    if (!hasPath)
                    {
                        sb.AppendLine($"  <!-- Layer '{layer.Name}' has no texture path — skipped -->");
                        sb.AppendLine();
                        continue;
                    }

                    // Produce a safe defName: SceneObject_LayerName_Priority
                    string safeLayerName = layer.Name.Replace(" ", "_");
                    string defName = $"{obj.DefName}_{safeLayerName}_{layer.Priority}";

                    sb.AppendLine($"  <!-- Layer {layer.Priority}: {layer.Name}"
                                + (layer.Visible ? "" : " [HIDDEN]") + " -->");
                    sb.AppendLine($"  <ThingDef ParentName=\"BuildingBase\">");
                    sb.AppendLine($"    <defName>{defName}</defName>");
                    sb.AppendLine($"    <label>{layer.Name.ToLower()}</label>");

                    sb.AppendLine("    <graphicData>");
                    sb.AppendLine($"      <texPath>{layer.TexturePath}</texPath>");

                    string gfxClass = layer.IsDirectional ? "Verse.Graphic_Multi" : "Verse.Graphic_Single";
                    sb.AppendLine($"      <graphicClass>{gfxClass}</graphicClass>");

                    // Draw size: layer scale multiplied by the object's root scale.
                    float dsX = layer.Scale.x * obj.RootScale.x;
                    float dsY = layer.Scale.y * obj.RootScale.y;
                    sb.AppendLine($"      <drawSize>({dsX:F3},{dsY:F3})</drawSize>");

                    // Draw offset: layer position + root position (Y→Z axis conversion).
                    float doX = layer.Position.x + obj.RootPosition.x;
                    float doZ = layer.Position.y + obj.RootPosition.y;
                    if (doX != 0f || doZ != 0f)
                        sb.AppendLine($"      <drawOffset>({doX:F4},0,{doZ:F4})</drawOffset>");

                    // Color tint (skip if pure white).
                    if (!ColorIsWhite(layer.Color))
                        sb.AppendLine($"      <color>({layer.Color.r:F3},{layer.Color.g:F3},{layer.Color.b:F3},1)</color>");

                    sb.AppendLine("    </graphicData>");

                    // Extra properties as comments so they're not lost.
                    if (layer.Opacity < 1f)
                        sb.AppendLine($"    <!-- opacity: {layer.Opacity:F2} (not natively supported in vanilla XML) -->");
                    if (layer.Rotation != 0f)
                        sb.AppendLine($"    <!-- rotation: {layer.Rotation:F1}° -->");
                    if (!string.IsNullOrEmpty(layer.BodyTypeVariant))
                        sb.AppendLine($"    <!-- bodyTypeVariant: {layer.BodyTypeVariant} -->");

                    sb.AppendLine("    <altitudeLayer>BuildingOnTop</altitudeLayer>");
                    sb.AppendLine("    <passability>PassThroughOnly</passability>");
                    sb.AppendLine("    <fillPercent>0</fillPercent>");
                    sb.AppendLine($"    <!-- drawPriority hint: {layer.Priority} -->");
                    sb.AppendLine("  </ThingDef>");
                    sb.AppendLine();
                }
            }

            return WrapInDefsDocument(sb.ToString());
        }

        // ── 4. PAWNKINDDEF XML SNIPPET ────────────────────────────────────────

        public static string GeneratePawnKindXmlString(SceneObject obj)
        {
            if (obj == null) return "";

            // Find body and head layers by name convention.
            string bodyPath = FindLayerPath(obj, "Body") ?? (obj.Layers.Count > 0 ? obj.Layers[0].TexturePath : "");
            string headPath = FindLayerPath(obj, "Head") ?? "";

            var sb = new StringBuilder();
            sb.AppendLine("<PawnKindDef>");
            sb.AppendLine($"  <defName>{obj.DefName}</defName>");
            sb.AppendLine($"  <label>{obj.DefName.ToLower()}</label>");
            sb.AppendLine("  <race>Human</race>");
            sb.AppendLine("  <combatPower>50</combatPower>");
            sb.AppendLine("  <lifeStages>");
            sb.AppendLine("    <li>");
            if (!string.IsNullOrEmpty(bodyPath))
            {
                sb.AppendLine("      <bodyGraphicData>");
                sb.AppendLine($"        <texPath>{bodyPath}</texPath>");
                sb.AppendLine($"        <drawSize>{obj.RootScale.x:F2}</drawSize>");
                sb.AppendLine("      </bodyGraphicData>");
            }
            if (!string.IsNullOrEmpty(headPath))
            {
                sb.AppendLine("      <headGraphicData>");
                sb.AppendLine($"        <texPath>{headPath}</texPath>");
                sb.AppendLine("      </headGraphicData>");
            }
            sb.AppendLine("    </li>");
            sb.AppendLine("  </lifeStages>");
            sb.AppendLine("</PawnKindDef>");
            return sb.ToString();
        }

        // ── CORE GENERATOR — one Def per SceneObject ──────────────────────────

        private static string GenerateDefXmlString(SceneObject obj)
        {
            if (obj == null) return "";

            switch (obj.DefType)
            {
                case RimWorldDefType.PawnKindDef: return GeneratePawnKindXmlString(obj);
                case RimWorldDefType.FleckDef:    return GenerateFleckDef(obj);
                case RimWorldDefType.EffecterDef: return GenerateEffecterDef(obj);
                default:                          return GenerateThingDef(obj);
            }
        }

        // ── THINGDEF ──────────────────────────────────────────────────────────

        private static string GenerateThingDef(SceneObject obj)
        {
            var layer0 = obj.Layers.Count > 0 ? obj.Layers[0] : null;
            var sb = new StringBuilder();

            // Determine parent/category — best-effort heuristic from defName / template.
            string parentName = string.IsNullOrEmpty(obj.BaseTemplate)
                ? "BaseWeapon"          // safe fallback; user can edit
                : obj.BaseTemplate;

            sb.AppendLine($"<!-- Generated by RimRimModelEditor — edit defName and ParentName as needed -->");
            sb.AppendLine($"<ThingDef ParentName=\"{parentName}\">");
            sb.AppendLine($"  <defName>{obj.DefName}_Studio</defName>");
            sb.AppendLine($"  <label>{obj.DefName.ToLower()}</label>");

            // graphicData — driven by Layer 0 ("Base")
            if (layer0 != null && !string.IsNullOrEmpty(layer0.TexturePath))
            {
                sb.AppendLine("  <graphicData>");
                sb.AppendLine($"    <texPath>{layer0.TexturePath}</texPath>");

                // Guess graphicClass from directional flag
                string gfxClass = layer0.IsDirectional
                    ? "Graphic_Multi"
                    : "Graphic_Single";
                sb.AppendLine($"    <graphicClass>Verse.{gfxClass}</graphicClass>");

                // drawSize from RootScale
                sb.AppendLine($"    <drawSize>({obj.RootScale.x:F2},{obj.RootScale.y:F2})</drawSize>");

                // drawOffset — convert 2-D studio position to RimWorld's 3-D XZY format.
                if (obj.RootPosition != Vector2.zero)
                    sb.AppendLine(
                        $"    <drawOffset>({obj.RootPosition.x:F4},0,{obj.RootPosition.y:F4})</drawOffset>");

                // Colour tint if not pure white
                if (!ColorIsWhite(layer0.Color))
                    sb.AppendLine($"    <color>({layer0.Color.r:F3},{layer0.Color.g:F3},{layer0.Color.b:F3},1)</color>");

                sb.AppendLine("  </graphicData>");
            }

            // Weapon overrides
            if (obj.EquippedAngleOffset != 0f)
                sb.AppendLine($"  <equippedAngleOffset>{obj.EquippedAngleOffset:F1}</equippedAngleOffset>");

            // Per-layer comps — layers beyond index 0 become GraphicMeshSet overlays
            if (obj.Layers.Count > 1)
            {
                sb.AppendLine("  <!-- Additional layers from studio (manual integration required): -->");
                for (int i = 1; i < obj.Layers.Count; i++)
                {
                    var l = obj.Layers[i];
                    if (string.IsNullOrEmpty(l.TexturePath)) continue;
                    sb.AppendLine($"  <!-- Layer {i} '{l.Name}': texPath={l.TexturePath}"
                                 + $" pos=({l.Position.x:F3},{l.Position.y:F3})"
                                 + $" scale=({l.Scale.x:F2},{l.Scale.y:F2}) -->");
                }
            }

            sb.AppendLine("</ThingDef>");
            return sb.ToString();
        }

        // ── FLECKDEF ─────────────────────────────────────────────────────────

        private static string GenerateFleckDef(SceneObject obj)
        {
            var layer0 = obj.Layers.Count > 0 ? obj.Layers[0] : null;
            var sb = new StringBuilder();

            sb.AppendLine($"<!-- Generated by RimRimModelEditor -->");
            sb.AppendLine("<FleckDef>");
            sb.AppendLine($"  <defName>{obj.DefName}_Studio</defName>");
            sb.AppendLine($"  <label>{obj.DefName.ToLower()}</label>");

            if (layer0 != null && !string.IsNullOrEmpty(layer0.TexturePath))
            {
                sb.AppendLine("  <graphicData>");
                sb.AppendLine($"    <texPath>{layer0.TexturePath}</texPath>");
                sb.AppendLine($"    <graphicClass>Verse.Graphic_Single</graphicClass>");
                sb.AppendLine($"    <drawSize>({obj.RootScale.x:F2},{obj.RootScale.y:F2})</drawSize>");
                sb.AppendLine("  </graphicData>");
            }

            sb.AppendLine($"  <fadeInTime>{obj.FadeInTime:F2}</fadeInTime>");
            sb.AppendLine($"  <solidTime>{obj.SolidTime:F2}</solidTime>");
            sb.AppendLine($"  <fadeOutTime>{obj.FadeOutTime:F2}</fadeOutTime>");

            if (obj.GrowthRate != 0f)
                sb.AppendLine($"  <growthRate>{obj.GrowthRate:F2}</growthRate>");

            sb.AppendLine("</FleckDef>");
            return sb.ToString();
        }

        // ── EFFECTERDEF ──────────────────────────────────────────────────────

        private static string GenerateEffecterDef(SceneObject obj)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<!-- Generated by RimRimModelEditor -->");
            sb.AppendLine("<EffecterDef>");
            sb.AppendLine($"  <defName>{obj.DefName}_Studio</defName>");
            sb.AppendLine("  <children>");

            foreach (var layer in obj.Layers)
            {
                if (string.IsNullOrEmpty(layer.TexturePath)) continue;
                sb.AppendLine("    <li Class=\"SubEffecter_Sprayer\">");
                sb.AppendLine("      <fleckDef>DustPuff</fleckDef>"); // placeholder
                sb.AppendLine($"      <!-- texPath hint: {layer.TexturePath} -->");
                sb.AppendLine("    </li>");
            }

            sb.AppendLine("  </children>");
            sb.AppendLine("</EffecterDef>");
            return sb.ToString();
        }

        // ── HELPERS ──────────────────────────────────────────────────────────

        public static string WrapInDefsDocument(string inner)
        {
            return
$@"<?xml version=""1.0"" encoding=""UTF-8""?>
<Defs>

{inner.TrimEnd()}

</Defs>
";
        }

        private static string FindLayerPath(SceneObject obj, string nameContains)
        {
            foreach (var l in obj.Layers)
                if (l.Name.IndexOf(nameContains, StringComparison.OrdinalIgnoreCase) >= 0
                    && !string.IsNullOrEmpty(l.TexturePath))
                    return l.TexturePath;
            return null;
        }

        private static bool ColorIsWhite(Color c)
            => Mathf.Approximately(c.r, 1f) && Mathf.Approximately(c.g, 1f) && Mathf.Approximately(c.b, 1f);

        private static void CopySceneTextures(
            EditorState state, string outputDir, bool overwrite, List<string> errors)
        {
            string texOut = Path.Combine(outputDir, "Textures");
            Directory.CreateDirectory(texOut);
            foreach (var obj in state.ActiveScene)
            {
                foreach (var layer in obj.Layers)
                {
                    if (string.IsNullOrEmpty(layer.TexturePath) || !File.Exists(layer.TexturePath))
                        continue;
                    try
                    {
                        string dest = Path.Combine(texOut, Path.GetFileName(layer.TexturePath));
                        File.Copy(layer.TexturePath, dest, overwrite);
                    }
                    catch { errors.Add($"Texture '{layer.Name}' copy failed."); }
                }
            }
        }
    }
}
